CREATE TABLE IF NOT EXISTS `ejemplos`.`PROV-PROD`(
    `NUMERO` INT NOT NULL,
    `PNRO` INT NOT NULL,
    `CANTIDAD` INT NOT NULL,
    PRIMARY KEY (`NUMERO`, `PNRO`),
    FOREIGN KEY (`NUMERO`) REFERENCES PROVEEDORES(`NUMERO`),
    FOREIGN KEY (`PNRO`) REFERENCES PRODUCTOS (`PNRO`)
);